name: Docker Image CI

on:
  push:
    branches: [ dockerfile ]
  pull_request:
    branches: [ dockerfile ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - 
      uses: actions/checkout@v3
      name: Build the Docker image
    -
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
    -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:buildcache,mode=max
